apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-service
  name: backend-service
spec:
  ports:
    - name: backend-service-port
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}
