export const GET_CONTACT = `GET_CONTACT`;
export const GET_CONTACT_SUCCESS = `GET_CONTACT_SUCCESS`;
export const GET_CONTACT_FAIL = `GET_CONTACT_FAIL`;

export const DELETE_CONTACT = `DELETE_CONTACT`;
export const DELETE_CONTACT_SUCCESS = `DELETE_CONTACT_SUCCESS`;
export const DELETE_CONTACT_FAIL = `DELETE_CONTACT_FAIL`;

export const EDIT_CONTACT = `EDIT_CONTACT`;
export const EDIT_CONTACT_FAIL = `EDIT_CONTACT_FAIL`;
export const EDIT_CONTACT_SUCCESS = `EDIT_CONTACT_SUCCESS`;
